version: "3.8"
services:

  
  angular-app:
    image: angular-app-image
    container_name: angular-app
    build:
      context: ./angular-app
    ports:
      - "4200:80"
    networks:
      - mynetwork

  
  aprendiendo-angular:
    image: aprendiendo-angular-image
    container_name: aprendiendo-angular-app
    build:
      context: ./AprendiendoAngular
    ports:
      - "4201:80"
    networks:
      - mynetwork
  
  nginx-server:
    container_name: nginx-server
    image: nginx-image
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8000:80"
    networks:
      - mynetwork

  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    networks:
      - mynetwork
    volumes:
      - mydbdata:/var/lib/postgresql/data

  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pf@imunixx.de"
      PGADMIN_DEFAULT_PASSWORD: "yacJanAin7"
    ports:
      - 80:80
    depends_on:
      - postgres
    networks:
      - mynetwork
    volumes:
      - pgadmindata:/var/lib/pgadmin
      - ./pgadmin4:/root/.pgadmin



networks:
  mynetwork:
    driver: bridge


volumes:
  mydbdata:
  pgadmindata: