version: "3.8"
services:

  postgres:
    container_name: postgres
    image: docker.imunixx.de/postgres:12.8
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    networks:
      - mynetwork
    volumes:
      - mydbdata:/var/lib/postgresql/data

  
  pgadmin:
    container_name: pgadmin
    image: docker.imunixx.de/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pf@imunixx.de"
      PGADMIN_DEFAULT_PASSWORD: "yacJanAin7"
    ports:
      - 80:80
    depends_on:
      - postgres
    networks:
      - mynetwork
    volumes:
      - pgadmindata:/var/lib/pgadmin
      - ./pgadmin4:/root/.pgadmin

  back-end:
    container_name: back-end
    image: docker.imunixx.de/back-end-image
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork

  front-end:
    image: docker.imunixx.de/front-end-image
    container_name: front-end
    ports:
      - "4200:4200"
    depends_on:
      - back-end
    networks:
      - mynetwork

  nginx-server:
    container_name: nginx-server
    image: docker.imunixx.de/nginx:1.21.1-alpine
    ports:
      - "8000:8000"
    depends_on:
      - front-end
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
    name: mynetwork


volumes:
  mydbdata:
  pgadmindata: